apiVersion: apps/v1
kind: Deployment
metadata:
  name: webadmin-deployment
  labels:
    app: webadmin
  namespace: cp-dev-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webadmin
  template:
    metadata:
      labels:
        app: webadmin
    spec:
      containers:
        - name: webadmin
          image: $REGISTRY_HARBOR_URL/container-platform-new-dev/container-platform-webadmin:$BUILD_NUMBER
          imagePullPolicy: Always
          ports:
            - containerPort: 2090
          env:
            - name: K8S_IP
              value: K8S_IP
            - name: CONTAINER_PLATFORM_COMMON_API_URL
              value: CONTAINER_PLATFORM_COMMON_API_URL
            - name: CONTAINER_PLATFORM_API_URL
              value: CONTAINER_PLATFORM_API_URL
      imagePullSecrets:
        - name: paasta-cp-dev-secret
---
apiVersion: v1
kind: Service
metadata:
  name: webadmin-deployment
  labels:
    app: webadmin
  namespace: cp-dev-namespace
spec:
  ports:
    - nodePort: 32703
      port: 2090
      protocol: TCP
      targetPort: 2090
  selector:
    app: webadmin
  type: NodePort
